import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { AgentableConfig, ActionConfig, ParamConfig } from '@agentableui/core'

function paramTypeToTS(param: ParamConfig): string {
  switch (param.type) {
    case 'string': return 'string'
    case 'number': return 'number'
    case 'boolean': return 'boolean'
    case 'enum': return param.values!.map(v => `'${v}'`).join(' | ')
    default: return 'unknown'
  }
}

function generateActionType(action: ActionConfig): string {
  const parts: string[] = []

  // Params
  if (action.params && Object.keys(action.params).length > 0) {
    const paramEntries = Object.entries(action.params).map(([name, param]) => {
      const optional = param.required ? '' : '?'
      return `${name}${optional}: ${paramTypeToTS(param)}`
    })
    parts.push(`params: { ${paramEntries.join('; ')} }`)
  } else {
    parts.push(`params: {}`)
  }

  // Transitions
  if (action.transitions) {
    parts.push(`transitions: '${action.transitions}'`)
  }

  // Errors
  if (action.errors && action.errors.length > 0) {
    parts.push(`errors: ${action.errors.map(e => `'${e}'`).join(' | ')}`)
  }

  return `{ ${parts.join('; ')} }`
}

function quoteKey(key: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`
}

export async function generateHooks(config: AgentableConfig, outputDir: string): Promise<string> {
  const lines: string[] = []

  lines.push('// .agentable/hooks.ts — AUTO-GENERATED by @agentableui/cli, DO NOT EDIT')
  lines.push("import { createHooks } from '@agentableui/react'")
  lines.push('')
  lines.push('export type AppConfig = {')
  lines.push('  states: {')

  for (const [stateName, state] of Object.entries(config.states)) {
    lines.push(`    ${quoteKey(stateName)}: {`)
    lines.push('      actions: {')

    for (const [actionName, action] of Object.entries(state.actions)) {
      const actionType = generateActionType(action)
      lines.push(`        ${quoteKey(actionName)}: ${actionType}`)
    }

    lines.push('      }')
    lines.push('    }')
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export const {')
  lines.push('  AgentableProvider,')
  lines.push('  useAgentableState,')
  lines.push('  useAgentableAction,')
  lines.push('  useAgentableConditions,')
  lines.push('} = createHooks<AppConfig>()')
  lines.push('')

  const content = lines.join('\n')
  const filePath = join(outputDir, 'hooks.ts')
  await writeFile(filePath, content)
  return filePath
}
